[package]
name = "english-linguistic-pkg"
version = "0.1.0"
authors = ["k0pernicus <k0pernicus@0xc0ff33.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
